language: rust
rust:
  - stable
cache: cargo
script:
  - cargo build --all --all-targets --examples
  - cargo test
  - cargo run --example minimal
  - rustup target add thumbv6m-none-eabi
  - cargo build --target thumbv6m-none-eabi
