[package]
name = "simple_on_shutdown"
desription = "This crate consists of a convenient macro to specify on shutdown callbacks. It's super simple and stripped-down."
version = "0.1.0"
authors = ["Philipp Schuster <phip1611@gmail.com>"]
edition = "2018"
exclude = [
    ".travis.yml"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
